replicaCount: 2

container:
  port: 8080
  image:
    repository: your-registry/your-app
    tag: latest
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policy:
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      policy:
        value: 50
        periodSeconds: 30
  trigger:
    type: kafka
    metadata:
      bootstrapServers: "kafka:9092"
      topic: "my-topic"
      consumerGroup: "my-group"
      lagThreshold: "10"
      cpuThreshold: "80"
      memoryThreshold: "75"
