apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ required "service.type is required" .Values.service.type }}
  ports:
    - port: {{ required "service.port is required" .Values.service.port }}
      targetPort: {{ required "service.targetPort is required" .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
